spring: 
  profiles: 
    active:
    - dev

---
spring:
  profiles: dev
  application: 
    name: springcloud-config-atzhangbin-dev
---
spring:
  profiles: test
  application: 
    name: springcloud-config-atzhangbin-test
