spring: 
  profiles: 
    active:
    - dev

---
spring:
  prolfies: dev
  application: 
    name: springcloud-config-atzhangbin-dev
---
spring:
  prolfies: test
  application: 
    name: springcloud-config-atzhangbin-test